package me.atog.anr.plugin.types;

public enum Phase {
	ITEM_MATERIAL, ITEM_DATA, ITEM_NAME, ITEM_DESCRIPTION, ATTRIBUTE_DAMAGE, ATTRIBUTE_STRENGTH, ATTRIBUTE_SPEED, ABILITY, ACTION_ABILITY, RARITY, ENCHANTED
}
